services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  spring_boot:
    build:
      context: .
      dockerfile: Dockerfile
    image: jangtaehyeon/littlebank:latest
    container_name: littlebank_prod
    volumes:
      - /home/ubuntu/springboot-logs:/logs
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      - redis