services:

  spring_boot:
    build:
      context: .
      dockerfile: Dockerfile
    image: jangtaehyeon/littlebank:latest
    container_name: littlebank_prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
